name: test-action

on:
  workflow_dispatch:
  #schedule:
  # UTC, https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
  #- cron: '0/5 * * * *'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:          
      - name: Run a one-line script
        shell: bash
        env:
          REPO: ${{ github.event.repository.name }}
          OWNER: ${{ github.event.repository.owner.login }}
          PULL_ID: 21
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/mergePR.sh
